baseURL = "https://www.shrubcoop.org/"
languageCode = "en-gb"
pluralizelisttitles = "false"
publishDir = "docs"
theme = "shrub"
title = "SHRUB Coop"
[[menu.main]]
name = "Zero Waste Edinburgh"
parent = "about-us"
pre = "Click this link to find out about zero waste projects in and around Edinburgh."
url = "/zero-waste-edinburgh/"
weight = 1
[[menu.main]]
name = "Donate"
url = "/donate"
weight = 8
[[menu.main]]
identifier = "news"
name = "News"
pre = "This is the link to the Blog section of the site. Click here to read our latest blog posts"
url = "/news/"
weight = 5
[[menu.main]]
identifier = "about-us"
name = "About Us"
pre = "Click this link to find out about us and why we exist."
url = "/about-us/"
weight = 3
[[menu.main]]
identifier = "get-involved"
name = "Get Involved"
pre = "This is the link to the Get Involved section of the site. Click here to Volunteer with us, Sign up to our Newsletter or become a Member of Shrub."
url = "/get-involved/"
weight = 4
[[menu.main]]
identifier = "home"
name = "Home"
pre = ""
url = "/"
weight = 2
[[menu.main]]
identifier = "contact"
parent = "about-us"
name = "Contact"
pre = "This is the Contact section of the site. Click here to find out how to send us an email."
url = "/contact/"
weight = 7
[[menu.main]]
identifier = "resource-packs"
parent = "about-us"
name = "Resource Packs"
pre = "Click here to read our guides on zero waste activities."
url = "/resource-packs/"
weight = 9
[[menu.main]]
identifier = "events"
name = "Events"
pre = "This is the link to the Events section of the site. Click here to read about our latest events"
url = "/events/"
weight = 6
[[menu.socials]]
name = "Facebook"
url = "https://www.facebook.com/shrubcoop/"
weight = 1
[[menu.socials]]
name = "Instagram"
url = "https://www.instagram.com/shrubcoop/"
weight = 2
[[menu.socials]]
name = "Twitter"
url = "https://twitter.com/shrubcoop"
weight = 3
[params]
fundersFooterText = "SHRUB Coop is funded through the Scottish Government’s Climate Challenge Fund and the European Regional Development Fund. We’re grateful for all their support. Find out more about our funders by clicking on the logos above."
mapStyle = "streets-v11"
mapboxKey = "pk.eyJ1Ijoicm9zc2h1ZHNvbiIsImEiOiJjanpnMGE0MGowaGZtM2VsaXNjdWh2dWZmIn0.cNr_4alsLclO3Exj20P9sA"
murakamiCarbonKey = "UUGLwdSBrFutmfmBnA8ccC4BC"
murakamiMembershipSignUpKey = "wza96Xne2EUrmCucaM9qhaMMr"
murakamiRolesKey = "NAe5nwnJQFzKkGn8nFKYYANxS"
shrubLegalName = "SHRUB Cooperative, Scottish Charitable Incorporated Organisation (Scottish Charity Number SC048825)"
webmasterEmail = "webmaster@shrubcoop.org"

[[params.funders]]
name = "Climate Change Fund"
image = "ccf.jpg"
link = "https://www.keepscotlandbeautiful.org/sustainability-climate-change/climate-challenge-fund"

[[params.funders]]
name = "European Regional Development Fund"
image = "erdf.jpg"
link = "https://ec.europa.eu/regional_policy/en/funding/"

[[params.funders]]
name = "Greener Scotland"
image = "greener-scotland.jpg"
link = "https://www.greenerscotland.org"


[params.footer]

[params.footer.contact]

email = "hello@shrubcoop.org"
phoneNumber = "0131 220 1884"
streetAddress = "13 Guthrie Street"
postcode = "EH1 1JG"
city = "Edinburgh"

[taxonomies]
category = ["swapshop", "zero-waste-hub", "food-sharing", "wee-spoke-hub", "workshops-and-events"]
tag = ["swapshop", "zero-waste-hub", "food-sharing", "wee-spoke-hub", "workshops-and-events"]
