baseURL = "https://www.shrubcoop.org/"
languageCode = "en-gb"
pluralizelisttitles = "false"
publishDir = "docs"
theme = "shrub"
title = "SHRUB Coop"
[[menu.main]]
name = "Zero Waste Edinburgh Map"
parent = "about-us"
pre = "Click this link to find out about zero waste projects in and around Edinburgh."
url = "/zero-waste-edinburgh/"
weight = 1
[[menu.main]]
name = "Donate"
url = "/donate"
weight = 8
[[menu.main]]
identifier = "news"
name = "Our Blog"
pre = "This is the link to the Blog section of the site. Click here to read our latest blog posts"
url = "/news/"
weight = 5
[[menu.main]]
identifier = "about-us"
name = "About Us"
pre = "Click this link to find out about us and why we exist."
url = "/about-us/"
weight = 3
[[menu.main]]
identifier = "get-involved"
name = "Get Involved"
pre = "This is the link to the Get Involved section of the site. Click here to Volunteer with us, Sign up to our Newsletter or become a Member of Shrub."
url = "/get-involved/"
weight = 4
[[menu.main]]
identifier = "home"
name = "Home"
pre = ""
url = "/"
weight = 2
[[menu.main]]
identifier = "contact"
name = "Contact"
parent = "about-us"
pre = "This is the Contact section of the site. Click here to find out how to send us an email."
url = "/contact/"
weight = 7
[[menu.main]]
identifier = "resource-packs"
name = "Resource Packs"
parent = "about-us"
pre = "Click here to read our guides on zero waste activities."
url = "/resource-packs/"
weight = 9
[[menu.main]]
identifier = "events"
name = "Events"
pre = "This is the link to the Events section of the site. Click here to read about our latest events"
url = "/events/"
weight = 6
[[menu.socials]]
name = "Facebook"
url = "https://www.facebook.com/shrubcoop/"
weight = 1
[[menu.socials]]
name = "Instagram"
url = "https://www.instagram.com/shrubcoop/"
weight = 2
[[menu.socials]]
name = "Twitter"
url = "https://twitter.com/shrubcoop"
weight = 3
[params]
fundersFooterText = "SHRUB Coop is supported through a combination of grant funding and generous donations from our community. We’re grateful for all their support. Find out more about our grant funders by clicking on the logos above."
googleAnalyticsId = "G-FJ9PL78BGB"
mapStyle = "streets-v11"
mapboxKey = "pk.eyJ1Ijoicm9zc2h1ZHNvbiIsImEiOiJjanpnMGE0MGowaGZtM2VsaXNjdWh2dWZmIn0.cNr_4alsLclO3Exj20P9sA"
murakamiCarbonKey = "UUGLwdSBrFutmfmBnA8ccC4BC"
murakamiMembershipKey = "wza96Xne2EUrmCucaM9qhaMMr"
murakamiRolesKey = "NAe5nwnJQFzKkGn8nFKYYANxS"
shrubLegalName = "SHRUB Cooperative, Scottish Charitable Incorporated Organisation (Scottish Charity Number SC048825)"
webmasterEmail = "webmaster@shrubcoop.org"
[params.footer.contact]
city = "Edinburgh"
email = "hello@shrubcoop.org"
phoneNumber = "0131 281 0583"
postcode = "EH3 9AF"
streetAddress = "22 Bread Street"
[[params.funders]]
image = "https://res.cloudinary.com/shrub-co-op/image/upload/v1633603711/shrubcoop.org/media/peoplespostcodetrust_logo_iz9nzj.png"
link = "https://www.postcodetrust.org.uk/"
name = "People's Postcode Trust"
[[params.funders]]
image = "https://res.cloudinary.com/shrub-co-op/image/upload/v1614095261/shrubcoop.org/media/awards-for-all-Scotland.png_q7ikha.png"
link = "https://www.tnlcommunityfund.org.uk/funding/programmes/national-lottery-awards-for-all-scotland"
name = "National Lottery Awards for All Scotland"
[[params.funders]]
image = "https://res.cloudinary.com/shrub-co-op/image/upload/v1607544753/shrubcoop.org/media/the-gannochy-trust_upawyt.jpg"
link = "https://www.gannochytrust.org.uk/"
name = "The Gannochy Trust"
[[params.funders]]
image = "https://res.cloudinary.com/shrub-co-op/image/upload/v1607544351/shrubcoop.org/media/bos_uqqzdc.jpg"
link = "https://www.bankofscotlandfoundation.org/funding-programmes/reach"
name = "Bank of Scotland Foundation"
[[params.funders]]
image = "https://res.cloudinary.com/shrub-co-op/image/upload/v1607543448/shrubcoop.org/media/scsp_logo_strapline_v8vvld.jpg"
link = "https://www.pathsforall.org.uk/smarter-choices-smarter-places-1"
name = "Smarter Choices Smarter Places"
[[params.funders]]
image = "https://res.cloudinary.com/shrub-co-op/image/upload/v1631105598/shrubcoop.org/media/SG_master_logo_colour_CMYK_qwemmr.jpg"
link = "https://www.keepscotlandbeautiful.org/climate-change/climate-challenge-fund/"
name = "Climate Challenge Fund"
[taxonomies]
category = ["swapshop", "zero-waste-hub", "food-sharing", "wee-spoke-hub", "workshops-and-events"]
tag = ["swapshop", "zero-waste-hub", "food-sharing", "wee-spoke-hub", "workshops-and-events"]
