---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "{_index.md,about-us.md,contact.md,get-involved.md,zero-waste-edinburgh/_index.md,donate.md}"
  templates:
  - page
- type: heading
  label: Content
- type: directory
  path: content
  label: News
  create: all
  match: "*"
  exclude: "{_index.md,about-us.md,contact.md,get-involved.md}"
  templates:
  - blog
- type: directory
  path: content/events
  label: Events
  create: all
  match: "**/*"
- type: directory
  path: content/working-groups
  label: Working Groups
  create: all
  match: "**/*"
  templates:
  - working-group
- type: directory
  path: content/case-studies
  label: Case Studies
  create: all
  match: "**/*"
  templates:
  - case-study
- type: heading
  label: Volunteer Roles
- type: document
  path: content/volunteer/_index.md
  label: Volunteer Roles List Text
- type: document
  path: content/volunteer/view.md
  label: How To Apply Text
- type: heading
  label: Settings
- type: document
  path: config.toml
  label: Site Config
upload_dir: shrubcoop.org/media
public_path: https://res.cloudinary.com/shrub-co-op/image/upload
front_matter_path: https://res.cloudinary.com/shrub-co-op/image/upload
use_front_matter_path: true
file_template: ":filename:"
instant_preview: false
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.53
  preview_output_directory: public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: '0.53'
